### ISSUE TITLE
🚨 URGENT: GitHub Actions missing permissions configuration (Security Risk)

### ISSUE THREAD

**Issue by kanghouchao** [kanghouchao/japan-life-guide#13]
### **Problem Description**
GitHub CodeQL security scanning has detected that our GitHub Actions workflow (`deploy.yml`) does not limit the permissions of the `GITHUB_TOKEN`, which violates the principle of least privilege.

### **Security Risk Details**

**Location**: `.github/workflows/deploy.yml`
**Issue**: No explicit `permissions` block defined

**Current Configuration**:
```yaml
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    # ❌ Missing permissions block
```

**Risk Assessment**:
- **Severity**: 🔴 HIGH  
- **Impact**: Excessive permissions could allow unauthorized access to repository resources
- **Compliance**: Violates security best practices and principle of least privilege
- **CVSS**: 5.5-6.0 (Medium-High)

### **Why This Matters**

1. **Default Permissions**: Without explicit permissions, the workflow inherits repository-level permissions
2. **Organization Risk**: Repositories under organizations may inherit organization-wide permissions  
3. **Legacy Risk**: Repositories created before February 2023 default to read-write permissions
4. **Attack Surface**: Overprivileged tokens increase potential damage from compromised workflows

### **Required Fix**

**Option 1: Job-Level Permissions (Recommended)**
```yaml
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    permissions:
      contents: read        # Read repository content
      pull-requests: read   # Read PR information
      actions: read         # Read workflow information
      # No write permissions needed for deployment

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # ... rest of steps
```

**Option 2: Workflow-Level Permissions**
```yaml
name: Deploy to NGINX server

permissions:
  contents: read
  pull-requests: read
  actions: read

on:
  pull_request:
    types: [closed]
    # ... rest of configuration
```

### **Analysis of Required Permissions**

For our deployment workflow, we only need:
- ✅ `contents: read` - To checkout and read source code
- ✅ `pull-requests: read` - To check if PR is merged
- ✅ `actions: read` - To access workflow context

**NOT needed**:
- ❌ `contents: write` - We don't modify repository
- ❌ `pull-requests: write` - We don't update PRs
- ❌ `issues: write` - We don't manage issues
- ❌ `packages: write` - We don't publish packages

### **Implementation Steps**

1. **Immediate Fix** (within 2 hours):
   ```bash
   # Edit the workflow file
   # Add permissions block to .github/workflows/deploy.yml
   ```

2. **Validation**:
   - [ ] Verify workflow still functions correctly
   - [ ] Test with next PR merge
   - [ ] Confirm no permission errors

3. **Documentation**:
   - [ ] Update security documentation
   - [ ] Add security section to README

### **Files to Modify**
- ✅ `.github/workflows/deploy.yml` (Primary fix)
- ✅ `README.md` (Add security note)
- ✅ `docs/` (Security documentation update)

### **Security Best Practices**

Going forward, all GitHub Actions workflows should:
- 🔒 **Always specify explicit permissions**
- 🔒 **Use minimal required permissions**  
- 🔒 **Regularly audit workflow permissions**
- 🔒 **Document permission requirements**

### **References**
- [GitHub Actions Security Hardening](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions)
- [GITHUB_TOKEN Permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token)
- [Principle of Least Privilege](https://en.wikipedia.org/wiki/Principle_of_least_privilege)

### **Compliance Impact**
This issue affects:
- 🔒 **Security Audit Requirements**
- 🔒 **DevSecOps Best Practices**  
- 🔒 **CI/CD Security Standards**
- 🔒 **Organization Security Policies**

---

**⚠️ This security issue requires immediate attention to reduce attack surface and comply with security best practices.**
